#ifndef CONFIG_H
#define CONFIG_H

#define PEACHOS_KERNEL_LOCATION 0x100000
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define KERNEL_LONG_MODE_CODE_SELECTOR 0x18
#define KERNEL_LONG_MODE_TSS_SELECTOR 0x38

#define KERNEL_LONG_MODE_CODE_GDT_INDEX  3
#define KERNEL_LONG_MODE_DATA_GDT_INDEX 4
#define KERNEL_LONG_MODE_TSS_GDT_INDEX 7

#define TSS_DESCRIPTOR_TYPE 0x89  // 0x9 = 64-bit, bit 7 present
#define PEACHOS_TOTAL_INTERRUPTS 512


// 16 Bit number defining the total number of loaded
// entries. 
#define PEACHOS_MEMORY_MAP_TOTAL_ENTRIES_LOCATION 0x210000

// Where to find the E820 records
#define PEACHOS_MEMORY_MAP_LOCATION 0x210008

// 100MB heap size
#define PEACHOS_HEAP_MINIMUM_SIZE_BYTES 104857600
#define PEACHOS_HEAP_BLOCK_SIZE 4096

// The minimal address the heap can point at, ensuring
// that the kernel does not get overwritten
#define PEACHOS_MINIMAL_HEAP_ADDRESS 0x01100000

// This is a minimal heap table starting address
#define PEACHOS_MINIMAL_HEAP_TABLE_ADDRESS 0x01000000

#define PEACHOS_MINIMAL_HEAP_TABLE_SIZE PEACHOS_MINIMAL_HEAP_ADDRESS-PEACHOS_MINIMAL_HEAP_TABLE_ADDRESS


#define PEACHOS_SECTOR_SIZE 512

#define PEACHOS_MAX_FILESYSTEMS 12
#define PEACHOS_MAX_FILE_DESCRIPTORS 512

#define PEACHOS_MAX_PATH 108

#define PEACHOS_TOTAL_GDT_SEGMENTS 6

#define PEACHOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define PEACHOS_USER_PROGRAM_STACK_SIZE 1024 * 16
#define PEACHOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define PEACHOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END PEACHOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - PEACHOS_USER_PROGRAM_STACK_SIZE

#define PEACHOS_MAX_PROGRAM_ALLOCATIONS 1024
#define PEACHOS_MAX_PROCESSES 12

#define USER_DATA_SEGMENT 0x33 // Also includes requested privilage level 3 
#define USER_CODE_SEGMENT 0x2B // Also includes RPL3

#define PEACHOS_MAX_ISR80H_COMMANDS 1024

#define PEACHOS_KEYBOARD_BUFFER_SIZE 1024

#define WINDOW_MAX_TITLE 128
#define WINDOW_BORDER_PIXEL_SIZE 2
#define WINDOW_TITLE_BAR_HEIGHT 32
#endif